on: push
concurrency:
  group: ci-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
name: Build on push
jobs:
  tests-unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@0.0.1
      - name: Install deps
        run: |
            sudo -E env "PATH=$PATH" make deps &&
            sudo pip install j2cli
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          install-only: true
      - name: Build test
        run: sudo -E env "PATH=$PATH" make multiarch-build

      - name: Tests
        run: |
          sudo -E env "PATH=$PATH" make test-coverage
